export const genres = [
  { label: "Action", value: "action" },
  { label: "Adventure", value: "adventure" },
  { label: "Animation", value: "animation" },
  { label: "Biography", value: "biography" },
  { label: "Comedy", value: "comedy" },
  { label: "Crime", value: "crime" },
  { label: "Documentary", value: "documentary" },
  { label: "Drama", value: "drama" },
  { label: "Family", value: "family" },
  { label: "Fantasy", value: "fantasy" },
  { label: "Film-Noir", value: "filmnoir" },
  { label: "History", value: "history" },
  { label: "Horror", value: "horror" },
  { label: "Music", value: "music" },
  { label: "Musical", value: "musical" },
  { label: "Mystery", value: "mystery" },
  { label: "Romance", value: "romance" },
  { label: "Sci-Fi", value: "scifi" },
  { label: "Sport", value: "sport" },
  { label: "Thriller", value: "thriller" },
  { label: "War", value: "war" },
  { label: "Western", value: "western" },
];

export const RECOMMENDATIONS_COUNT = 5;
